defaults:
  - _self_
  - override hydra/launcher: basic

hydra:
  run:
    dir: plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
  sweep:
    dir: plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
    subdir: ${hydra.job.num}

ckpt_base_path: ./checkpoints
model_name: null
model_epoch: latest

seed: 99
n_evals: 8
goal_source: 'random_state'
goal_H: 5
n_plot_samples: 4

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 1
  base: 1
  mode: last
  probe_lambda: 0.0

planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: null
  n_taken_actions: 5
  sub_planner:
    target: planning.cem.CEMPlanner
    horizon: 5
    topk: 16
    num_samples: 64
    var_scale: 1
    opt_steps: 5
    eval_every: 1
  name: mpc_cem
